Playing videos
Tiahui-Tech/webtorrent-animeton pull request #10
Opened 2024-08-23 00:51 UTC by iAsure

2024-08-27 02:10 UTC, eKoh951 requested changes
Corrige lo que te marque en el codigo.

Por cierto, ando observando el codigo legacy de webtorrent, se comparte el `state` desde `webtorrent-animerso\src\renderer\lib\state.js`, eso se hacia asi por el paquete `location-history`, ya no se necesita porque usamos ahora `react-router` pero lo menciono porque es algo que debemos de mejorar en el futuro cercano para no hacer un codigo innecesariamente complejo y nos merme la productividad en el futuro.

Aqui ire anotando los issues para mejorar las cosas despues de que saquemos el MVP:
[Cleanup y mejorar dev experience del proyecto](https://linear.app/tiahui/project/cleanup-y-mejorar-dev-experience-del-proyecto-b1e6873eaa55/overview)

2024-08-27 02:10 UTC, eKoh951 commented on src/renderer/pages/player-page.js
> +  // console.log('Player state', state)
limpia log

2024-08-27 02:10 UTC, eKoh951 commented on src/renderer/pages/player-page.js
> +      {/* {renderOverlay(state)} */}
remueve este codigo si ya no se usa, y tambien la funcion si tampoco se usa

2024-08-29 23:05 UTC, iAsure commented on src/renderer/pages/player-page.js
> +      {/* {renderOverlay(state)} */}
Listo, por ahora no borre la funcion ya que si la vamos a necesitar a futuro

Solo que por ahora esta algo bug

2024-08-30 02:00 UTC, merged