MVP v0.0.6
Tiahui-Tech/webtorrent-animeton pull request #28
Opened 2024-10-16 02:01 UTC by iAsure

2024-10-16 18:39 UTC, eKoh951 requested changes
checate los comentarios, si te hace sentido cambiar las cosas, hazlo, como a mi me falta trabajar en el codigo no tengo mucha idea de que onda, asi que te lo dejo a tu criterio

2024-10-16 18:39 UTC, eKoh951 commented on src/renderer/components/episode/EpisodesList/index.js
> +    let result = Array.isArray(episodesData) ? [...episodesData] : [];
Mmm esto se me hace curioso, por ejemplo si el result al final hace fallback a un array vacio, no me da mucho sentido que abajo lo filtre, porque es un array vacio

en todo caso deberia de terminar la ejecucion y devolver un array vacio si episodeData no es un array o en su lugar tirar error o algo por el estilo, eso puede dar paso a un bug en el que esperas algo

2024-10-16 18:39 UTC, eKoh951 commented on src/renderer/controllers/subtitles-controller.js
> +
esto no estoy seguro pero si es un error, deberia hacer print tipo console.error si es un error

un warning si es algo esperado

le sirve a mario que identifique mas facil algunas cosas

2024-10-16 18:39 UTC, eKoh951 commented on src/renderer/pages/player-page.js
> +  const prog = state.getPlayingTorrentSummary()?.progress || {};
hay que tener cuidado con estos fallbacks a valores vacios, pueden generar bugs si mas adelante esperamos un objeto con ciertos valores, no es un problema pero como tenemos javascript en lugar de typescript, chance haya codigo que trata de acceder a un param de este objeto y ahi truene

solo lo menciono, no hay un verdadero problema pero para que lo tengas en cuenta

2024-10-17 20:07 UTC, iAsure commented on src/renderer/components/episode/EpisodesList/index.js
> +    let result = Array.isArray(episodesData) ? [...episodesData] : [];
@eKoh951 Es verdad, ya lo mejore

Anteriormente lo deje asi ya que habia sido un quick fix cuando la api no retornaba los episodios

2024-10-17 20:08 UTC, iAsure commented on src/renderer/controllers/subtitles-controller.js
> +
@eKoh951 Esto es una stop a la fuerza, ya que a veces intentaba obtener subititulos cuando el episodio ya no existia, entonces esto detiene el bucle

2024-10-17 20:40 UTC, eKoh951 approved these changes
arre se ve bien 👍

2024-10-17 20:41 UTC, merged