Anime Details Page
Tiahui-Tech/webtorrent-animeton pull request #5
Opened 2024-08-02 01:17 UTC by iAsure

2024-08-13 05:13 UTC, eKoh951 requested changes
Considera usar esta libreria de `react-window` para optimizar el rendimiento:
https://github.com/bvaughn/react-window

Esa lo que hace es unicamente cargar en la UI lo que se esta viendo en la pantalla unicamente, por ejemplo en anime details se compromete el rendimiento, va medio lentillo.

Igual eso me parece bien meterlo despues, siento que es mas importante planear el proyecto y poner esto de optimizacion dentro de la planeacion.

2024-08-13 05:13 UTC, eKoh951 commented on src/config.js
> +
Borra el log

2024-08-13 05:13 UTC, eKoh951 commented on src/modules/utils.js
> +const sortColorsByBrightness = (colors) => {
Bien aqui nombrando el nombre de la funcion, la logica esta bien rara pero con el nombre ya uno se da cuenta de que onda

2024-08-13 05:13 UTC, eKoh951 commented on src/renderer/components/AnimeRecommendations/index.js
> +  const recommendations = useAnimeRecommendations(idAnil);
Buen uso de hook para hacer mas sencilla la lectura del componente

2024-08-13 05:13 UTC, eKoh951 commented on src/renderer/components/AnimeRecommendations/index.js
> +        )}
Este codigo se me hace raro y medio feo, mira esto esta mas pro, usando el optional chaining `?.` :

```js
{recommendations?.map((anime, i) => (
  <AnimeCard
    key={`anim-recomm-${idAnil}-${i}`}
    anime={anime}
    state={state}
    glassStyle={genGlassStyle('#575757')}
  />
))}
```

Mas ricolino, ya si quieres con fallback:

```js
{recommendations?.length ? (
  recommendations.map((anime, i) => (
    <AnimeCard
      key={`anim-recomm-${idAnil}-${i}`}
      anime={anime}
      state={state}
      glassStyle={genGlassStyle('#575757')}
    />
  ))
) : (
  <p>No hay recomendaciones disponibles uwu.</p>
)}
```

2024-08-13 05:13 UTC, eKoh951 commented on src/renderer/components/AnimeSection/anime.js
> +    navigate(`/anime-details/${anime.idAnil}`, {
Mejor usa `idAnilist` en lugar de `idAnil`, es mejor ser mas explicito para que los demas desarrolladores puedan entender de que trata este parametro, si no conocen que es anilist, estarian muy confundidos

---

Usa mejor `/anime/details/:idAnilist` que `/anime-details/:idAnil`

Esto ya es mas de preferencia personal pero casi creo que tambien aplica para SEO, por ejemplo lo que dice claude, concuerdo con el:

1. **Jerarquía clara**: Esta estructura refleja una jerarquía clara. Tienes un recurso principal "anime" y luego un subrecruso o una acción "details". Esto hace que la estructura de tu API o de tus rutas sea más intuitiva y fácil de entender.

2. **Escalabilidad**: Si en el futuro necesitas añadir más rutas relacionadas con anime, esta estructura te permite hacerlo de manera organizada. Por ejemplo:

`/anime/list`
`/anime/search`
`/anime/categories`


3. **Consistencia**: Mantiene una consistencia con las convenciones de diseño de API RESTful, donde los recursos se representan en plural y las acciones o sub-recursos vienen después.
Legibilidad: Es más fácil de leer y entender a primera vista. "anime" es claramente el recurso principal, y "details" es la acción o vista específica que estamos solicitando.

4. **Mantenibilidad**: Si decides en el futuro reorganizar o refactorizar tu estructura de rutas, tener esta jerarquía clara hace que sea más fácil mover o ajustar las rutas sin romper la lógica general.

2024-08-13 05:13 UTC, eKoh951 commented on src/renderer/components/EpisodesList/episode.js
Ah oye tambien por ejemplo, esto es como una "convencion" pero cuando tienes un `EpisodeList`, los hijos suelen ser `EpisodeItem`, sirve para distinguir quien es quien, aqui por la estructura del proyecto me doy cuenta que este archivo es el item pero si lo veo como `Episode` o solo `episode.js` pues igual y si me doy cuenta xd pero te paso el tip de la convecion que se usa en react

2024-08-13 05:13 UTC, eKoh951 commented on src/renderer/components/LatestEpisodesAside/index.js
> +          : Array.from({ length: 8 }).map((_, i) => (
Aqui solo agrega como comentario tipo:

```js
// While loading, shows 8 EpisodeSkeletons per row
```

Solo para que sea claro que es lo que hace

Dato curioso, si sabes porque en el `.map((_, i)` se pone el `_`? es porque cuando tu pones un _ significa que no necesitas esa variable, aqui no se usa esa pero necesitamos ponerla explicitamente porque necesitamos el indice `i`.

Tambien si quieres ser mas explicito en vez de poner `_` puedes poner `_emptyValue` o algo por el estilo pero creo que eso ya es mucho, es tipo para que los mas juniors entiendan que show

2024-08-13 05:13 UTC, eKoh951 commented on src/renderer/components/header.js
> +    // Actualiza el estado de navegación cada vez que cambia la ubicación o el tipo de navegación
Cambia el comentario a ingles, este si esta bien por que la logica de abajo se ve rarona

2024-08-13 05:13 UTC, eKoh951 commented on src/renderer/components/header.js
> +      {getTitle()}
Creo que puedes hacer uso de un react mas moderno aca en lugar de llamar a `getTitle` tipo:

```jsx
      {process.platform === 'darwin' && (
        <div className="title ellipsis" title={state.window.title}>
          {state.window.title}
        </div>
      )}
```
Y ya no tenemos que subir a leer lo que hace la funcion para entender que onda

2024-08-13 05:13 UTC, eKoh951 commented on src/renderer/components/header.js
> +        {getAddButton()}
Lo mismo de arriba pero con esto:
```jsx
{location.pathname === '/' && (
  <i
    className="icon add"
    title="Add torrent"
    onClick={dispatcher('openFiles')}
    role="button"
  >
    add
  </i>
)}
```

2024-08-13 05:13 UTC, eKoh951 commented on src/renderer/hooks/useAnimeDetails.js
> +const useAnimeDetails = (anilId) => {
`anilId` -> `anilistId`

2024-08-13 19:31 UTC, iAsure commented on src/modules/utils.js
> +const sortColorsByBrightness = (colors) => {
Jajaja gracias

2024-08-13 19:32 UTC, iAsure commented on src/renderer/components/AnimeRecommendations/index.js
> +        )}
Mi error, iba agregar un Skeleton para AnimeCard y se me termino olvidando, ahi lo corrijo que ya tengo el Skeleton programado

2024-08-13 19:33 UTC, iAsure commented on src/renderer/components/AnimeSection/anime.js
> +    navigate(`/anime-details/${anime.idAnil}`, {
Perfecto, estare cambiando eso en la API tmb, es rapido

2024-08-13 19:34 UTC, iAsure commented on src/renderer/components/LatestEpisodesAside/index.js
> +          : Array.from({ length: 8 }).map((_, i) => (
Smn, si conocia el uso de `_`, es bastante util la vdd solo que rara la vez lo he utilizado

Gracias men uwu

2024-08-13 19:35 UTC, iAsure commented on src/renderer/components/header.js
> +    // Actualiza el estado de navegación cada vez que cambia la ubicación o el tipo de navegación
E smn, ese lo adapte rapidamente con Claude cuando pase el codigo de LocationHistory a React Router, mi error

2024-08-14 01:01 UTC, eKoh951 approved these changes
Se ve con madres 👌

2024-08-14 01:01 UTC, merged